### ISSUE TITLE
Plugin broken with Custom Pinegrow workspace (multi Monitor) and breaks Pinegrow Native Code editor/CSS Stylesheet view in Native Code editor

### ISSUE THREAD

**Issue by schpengle** [ehigiepaul/PGDevTool#6]
Confirming the above and also adding.

1. Adding that Custom Pinegrow workspace layout breaks the appearing of the Plugins Monaco editor, it does not even appear when pressing F7, and so cant be confirmed as empty - although previously this behaviour was noted.

2. Loading and Activating the Monaco editor plugin, with a custom Workspace layout (here, dual monitors, custom 
workspace) actually BREAKS the default  Pinegrow Editors ability to open and view the CSS stylesheets through the usual method. Instead, the Freshly opened CSS Stylesheet tabs, that usually open NEXT to the open Page, code view appear bizarrely above the tree panel view - and cannot be selected.

3. If these misplaced CSS Stylesheet tabs are dragged first to the boundary between 2 panels, then to where they should actually be (I think - this is the place where the Monaco editor appears -when it appears) they are once more empty - like the Monaco editor would be, in this current Beta state, if it was to be present. It is as though after loading the plugin, it *takes* that space, fails to render content, and then prevents the default app from actually rendering its own content in that place too - to the point that even the new tabs cant be created in that same place.

4. only completely unloading the plugin helps to resolve this. deactivating does not help and, after unloading and reloading when having only deactivated, but NOT unloaded, Pinegrow will load, but complain in 3 stages about broken workspace layouts and force the User to restart the App.

following are some diagrams to hopefully explain and even more hopefully, in the right order! :-)

The Following is actually the right monitor, mislabelled by my good self!

![image](https://user-images.githubusercontent.com/3315030/108114408-a7ef2000-7090-11eb-8749-a8cd27ebbb9c.png)

in this, an element has been selected in layout pane (on the other,left hand monitor, as seen in next picture that follows) and in the CSS style editor pane (This, right hand monitor - mislabelled as left)  I am attempting to open the Stylesheet in the PG native Editors Code view pane.
I see nothing happening where I expect, the tab to appear (over on the left monitor -code view, editor pane), but see some movement somewhere, so expand and move panels, then notice the misplaced Stylesheet code view tabs have appeared above the tree view pane! partially obscuring the Tree panes search function box.

as is seen here.
![image](https://user-images.githubusercontent.com/3315030/108114862-3e234600-7091-11eb-894b-6f067cf2cbcb.png)

And AFTER dragging these stylesheet tabs from the top of the Tree view, This **startstyles.css** artefact was left on the screen unable to move it, the editor has been closed.

**NOTE** I am unable to drag the tab to where I THINK it should be (I think the correct place) -next to the HTML code editor tab - it will not lock in place there. ONLY below (with my custom layout) on the 
INDIVIDUAL ELEMENT's code view panel. I don't think this is the correct place, but this is where I CAN lock it.
BUT -this artefact is then left behind, here, after closing and THIS is the place where, for me, in my custom workspace layout, the Monaco editor sometimes appears (when the winds are good! standard layouts etc) so there appears to be some conflict with this space.

![image](https://user-images.githubusercontent.com/3315030/108115871-a4f52f00-7092-11eb-960a-434c390b87a1.png)

I now have to restart PG, as the NATIVE Pinegrow CSS STYLESHEET view no longer works at all.
I had to unload the plugin as Deactiving plugin alone did not work.

And then, when trying to reload Pinegrow, while STILL having the plugin LOADED (but deactivated) the following sequence of events is noted, before having to unload the plugin altogether and then restarting it.

![Screenshot 2021-02-16 at 19 01 23](https://user-images.githubusercontent.com/3315030/108116194-1d5bf000-7093-11eb-808d-2720e7f3a482.png)

![Screenshot 2021-02-16 at 19 04 20](https://user-images.githubusercontent.com/3315030/108116272-36fd3780-7093-11eb-872a-e23592948ff9.png)

![Screenshot 2021-02-16 at 19 05 11](https://user-images.githubusercontent.com/3315030/108116288-3fee0900-7093-11eb-95ed-5856e9e1b2b6.png)

**NOTE**

If I revert to a single monitor and default workspace then the Plugin's Monaco Editor pane DOES become visible with F7, but fails to render any contents.

_Originally posted by @schpengle in https://github.com/ehigiepaul/PGDevTool/issues/1#issuecomment-780090598_

**Comment by tenluap** [comment]
this a layout issue. Reworking the layout now.

**Comment by schpengle** [comment]
UPDATE

While testing the Monaco Editor plugin, I actually discovered a bug in Pinegrow itself, with Undocked Panels /custom workspace that broke the Pinegrow's Visual Editors ability to render overwritten /duplicated CSS styles correctly.

So Custom Layout implementation, effects Visual Editor's ability to render code state logic (greyed out/struck through if overwritten.) correctly.
Also, it broke the relationship between The content of the Visual tool , and the Native Text editor itself.

Ie, differing numbers of the same duplicated (body) style rulesets were appearing in both the visual editor and Text editor displays. (3 rulesets in one, 4 in the other)

Referenced here

https://forum.pinegrow.com/t/duplicate-style-ruleset-not-working-correctly-update-not-solved-it-reverted-then-sorted-iteself/4980/23?u=schpengle

This is now a recognised bug, and is being worked on by the Pinegrow team, but this, or its future fix, may hinder the correct function of this Monaco Editor Plugin, so I am writing here, to update this informatioin, incase this Monaco Editor Plugin is being debugged, in order to work around an actual Pinegrow bug.. which may soon be fixed, rendering the Monaco plugins work on a fix, redundant, or the Pinegrow fix may itself, break this plugin again.

This is updated/mentioned since, the custom workspace layout of Pinegrow seemed to interfere with this Monaco Plugin's functionality, yet, the Pinegrow custom workspace is itself, actually now shown to have a bug.

Maybe wait until/track the Pinegrow fix for the above, or check in with PineGrow devs about the fix and if it will affect your plugins implementation/ability to function first.

So the Pinegrow app has both a layout and visual editor /code editor contents disparity bug, which interfere with each other - before this Plugin even tries to function correctly in the app.

**Comment by tenluap** [comment]
https://github.com/ehigiepaul/PGDevTool/issues/1#issuecomment-788853237
