### ISSUE TITLE
Terminal Windows 10 PGDevTool-v1.8.0

### ISSUE THREAD

**Issue by Allmedialab** [ehigiepaul/PGDevTool#7]
Hi Paul,

*When I open the terminal with a pre build system loaded as a project in Pinegrow the terminal I'm not able to copy paste code in the terminal. 
*When I type in: npm install --global gulp-cli I get a npm ERR! code E404
*Managed to do npm install --global gulp-cli and npm install, but when I give a gulp or gulp dev command there are security errors appearing on screen.
*It's not easy to get the cursor working in the terminal you have to click multiple times
*Have to restart Pinegrow multiple times to be able to open a project
*Scroll field height of the terminal is to low! Preferable auto height

*I can type in: node to get in the Node shell
*I can type in: node --version and get the version dispayed
*I can type in: npm help and the help items appear, but are all over the place

Regards,
David

**Comment by tenluap** [comment]
ok will test this

**Comment by Allmedialab** [comment]
![error-gulp-terminal](https://user-images.githubusercontent.com/2815617/110235614-66d08a00-7f31-11eb-81f1-2aa311e424f3.png)

**Comment by Allmedialab** [comment]
Hi Paul,
I have edited some points of my previous post. This image shows the error I get when trying to "gulp" or "gulp dev" my build system. This is after the gulp cli is installed and everything needed to make it work.
Regards,
David

**Comment by tenluap** [comment]
Please can you try and run it on your powershell terminal and tell the result and also run it on CMD. 

I will like to know if the issue is from the extension or from your system scripting permission.

Thanks

**Comment by Allmedialab** [comment]
Hi Paul,

The best is try it your self to see if you can **gulp** and **gulp dev** this build system:
https://github.com/JayeshLab/bootstrap-5-sass-gulp-4-boilerplate

On the Windows computer I test on I have the same building system running in Terminus from Sublime text!
I managed to clone the repository and install all needed stuff like gulp cli  etc. but as soon as I want to build the system with gulp or gulp dev I get a error (npm install doesn't work too:
![gulp-error](https://user-images.githubusercontent.com/2815617/110237203-db5bf680-7f3a-11eb-85f6-4fe601530ac4.png)

**Comment by tenluap** [comment]
Ok will test it

**Comment by Allmedialab** [comment]
And......do you experience the same issues?
